### ISSUE TITLE
[회원가입 화면] 회원가입 버튼 클릭 시 아이디(이메일)와 비밀번호를 서버로 전송한다.

### ISSUE THREAD

**Issue by ootr47** [boostcampwm2023/and09-PriceGuard#16]
### 요구사항

회원가입 버튼 클릭 시 아이디(이메일)와 비밀번호를 서버로 전송한다.

### 추가 자료

*추가 링크 및 자료는 여기 적어주세요*

**Comment by EunhoKang** [comment]
Resolved by #77
