### ISSUE TITLE
[개선] 안드로이드 피드백 개선사항 적용

### ISSUE THREAD

**Issue by EunhoKang** [boostcampwm2023/and09-PriceGuard#197]
### 요구사항

- [x] 로딩중일때 Detail 에서 버튼들 비활성화
- [x] Dynamic Theme을 지원하지 않는 OS의 경우 해당 View 비활성화
- [x] 상품, 상품추천 목록 전환시 스크롤 / SRL 오류 생기는거 수정
- [x] Navigation 렉걸리는거 최적화
- [x] Detail 페이지에서 Graph 영역이 세로로 슬라이드할 경우 스크롤 영역에 적용되도록 변경
- [ ] 화면 회전 시 다이얼로그가 사라지는 현상 수정
- [x] Detail 페이지에서 Scroll State가 초기화되는 현상 수정
- [x] Recommended쪽 RecyclerView의 itemAnimator와 Productlist 쪽의 것을 통일

**Comment by Taewan-P** [comment]
Navigation 렉걸리는것에 대한 답: https://stackoverflow.com/a/71185696

**Comment by EunhoKang** [comment]
그래프 영역 스크롤 문제는 라벨을 long touch에서만 뜨도록 변경하여 해결

https://github.com/Taewan-P/material-android-chart/pull/26
