### ISSUE TITLE
[상품 상세 화면] 제거 요청에 대한 응답 성공 시 목록에서 상품을 제거한다.

### ISSUE THREAD

**Issue by ootr47** [boostcampwm2023/and09-PriceGuard#46]
### 요구사항

제거 요청에 대한 응답 성공 시 목록에서 상품을 제거한다. (뷰 업데이트)

### 추가 자료

*추가 링크 및 자료는 여기 적어주세요*

**Comment by EunhoKang** [comment]
디자인 변경으로 인해 해당 이슈는 작업하지 않게 되었습니다.
