### ISSUE TITLE
[상품 상세 화면] 페이지를 새로고침하여 최신 데이터로 뷰를 업데이트할 수 있다.

### ISSUE THREAD

**Issue by sickbirdd** [boostcampwm2023/and09-PriceGuard#50]
### 요구사항

페이지를 새로고침하여 최신 데이터로 뷰를 업데이트할 수 있다.

### 추가 자료

*추가 링크 및 자료는 여기 적어주세요*

**Comment by EunhoKang** [comment]
Resolved by #115

**Comment by EunhoKang** [comment]
인터랙션 방식부터 재정의 필요

**Comment by EunhoKang** [comment]
Resolved by #136 
새로고침 방식은 위로 당기는 방식 사용
