### ISSUE TITLE
[목록 화면] 페이지를 새로고침하여 최신 데이터로 뷰를 업데이트할 수 있다.

### ISSUE THREAD

**Issue by sickbirdd** [boostcampwm2023/and09-PriceGuard#53]
### 요구사항

페이지를 새로고침하여 최신 데이터로 뷰를 업데이트할 수 있다.

### 추가 자료

*추가 링크 및 자료는 여기 적어주세요*

**Comment by EunhoKang** [comment]
Resolved by #110
